name: app
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

resolution: workspace

# Add regular dependencies here.
dependencies:
  katageri_ai:

dev_dependencies:
  lints:
  test:
