name: sparrow_clients
description: AI Clients for the Sparrow AI Framework
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^3.0.0
  http: ^1.4.0
  json_annotation: ^4.9.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  lints: ^6.0.0
  mockito: ^5.4.4
  test: ^1.24.0
  io: ^1.0.5
  path: ^1.9.1
  flutter_dotenv: ^5.2.1

